# Generated by Django 5.0.1 on 2024-07-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
