# Generated by Django 3.2.10 on 2023-12-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
