# Generated by Django 3.2.10 on 2024-01-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0003_shoe_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
