# Generated by Django 3.2.10 on 2024-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0004_shoe_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(max_length=650),
        ),
    ]
