# Generated by Django 5.0.1 on 2024-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0004_alter_shoeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
