# Generated by Django 3.2.10 on 2024-01-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0005_alter_shoe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='out_of',
            field=models.BooleanField(default=False),
        ),
    ]
