# Generated by Django 5.0.1 on 2024-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0006_shoe_out_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
