# Generated by Django 5.0.1 on 2024-02-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0007_alter_shoe_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(max_length=750),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
