# Generated by Django 5.0.1 on 2024-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0008_alter_shoe_description_alter_shoe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(max_length=1200),
        ),
    ]
