# Generated by Django 5.0.1 on 2024-02-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0010_shoeblacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoeBlacklist',
        ),
    ]
