# Generated by Django 5.0.1 on 2024-02-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0011_delete_shoeblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
