# Generated by Django 5.0.1 on 2024-02-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
