# Generated by Django 5.0.1 on 2024-02-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_profile_email_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
    ]
