# Generated by Django 5.0.1 on 2024-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('discount', models.IntegerField()),
                ('one_time', models.BooleanField(default=True)),
            ],
        ),
    ]
