# Generated by Django 3.2.10 on 2024-01-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instarec',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
