# Generated by Django 5.0.1 on 2024-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='models',
            field=models.JSONField(null=True),
        ),
    ]
