# Generated by Django 3.2.10 on 2024-01-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_shoe_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='shoe',
        ),
    ]
