# Generated by Django 3.2.10 on 2024-01-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
