# Generated by Django 3.2.10 on 2024-01-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
