# Generated by Django 3.2.10 on 2024-01-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.TextField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(default=None, max_length=350, null=True),
        ),
    ]
