# Generated by Django 3.2.10 on 2024-01-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
