# Generated by Django 5.0.1 on 2024-02-19 15:24

import django.core.validators
import django.db.models.deletion
import shipping.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[shipping.models._validate_alphanumeric_spaces])),
                ('last_name', models.CharField(max_length=25, validators=[shipping.models._validate_alphanumeric_spaces])),
                ('city', models.CharField(max_length=80, validators=[shipping.models._validate_alphanumeric_and_hyphen])),
                ('address', models.CharField(max_length=80, validators=[shipping.models._validate_alphanumeric_and_hyphen])),
                ('house_number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('postal_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
