# Generated by Django 3.2.10 on 2024-01-23 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shipping_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
