# Generated by Django 3.2.10 on 2024-01-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_shipping_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='email',
        ),
    ]
