# Generated by Django 5.0.1 on 2024-01-31 12:44

import shipping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_alter_shipping_address_alter_shipping_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='first_name',
            field=models.CharField(max_length=25, validators=[shipping.models._validate_alphanumeric_spaces]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='last_name',
            field=models.CharField(max_length=25, validators=[shipping.models._validate_alphanumeric_spaces]),
        ),
    ]
