# Generated by Django 5.0.1 on 2024-01-31 12:47

import shipping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_alter_shipping_first_name_alter_shipping_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(max_length=80, validators=[shipping.models._validate_alphanumeric_and_hyphen]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(max_length=80, validators=[shipping.models._validate_alphanumeric_and_hyphen]),
        ),
    ]
