# Generated by Django 5.0.1 on 2024-01-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_alter_shipping_address_alter_shipping_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
